In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
from google.colab import files
uploaded=files.upload()

Saving mtcars.csv to mtcars.csv

In [4]:
df = pd.read_csv('/content/mtcars.csv')

In [5]:
import warnings
warnings.filterwarnings('ignore')

In [7]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [9]:
df.nunique()

model    32
mpg      25
cyl       3
disp     27
hp       22
drat     22
wt       29
qsec     30
vs        2
am        2
gear      3
carb      6
dtype: int64

In [10]:
df.head()

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [11]:
df.shape

(32, 12)

In [12]:
df.isna().sum()

model    0
mpg      0
cyl      0
disp     0
hp       0
drat     0
wt       0
qsec     0
vs       0
am       0
gear     0
carb     0
dtype: int64

In [14]:
df['hp'] = df['hp'].fillna(df['hp'].mean())
df['wt'] = df['wt'].fillna(df['wt'].mean())
df['disp'] = df['disp'].fillna(df['disp'].mean())

In [15]:
df.dropna(inplace=True)

In [16]:
df.shape

(32, 12)

In [17]:
df = pd.get_dummies(df, drop_first=True)

In [18]:
df.head()

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,...,model_Merc 280C,model_Merc 450SE,model_Merc 450SL,model_Merc 450SLC,model_Pontiac Firebird,model_Porsche 914-2,model_Toyota Corolla,model_Toyota Corona,model_Valiant,model_Volvo 142E
0,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,...,False,False,False,False,False,False,False,False,False,False
1,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,...,False,False,False,False,False,False,False,False,False,False
2,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,...,False,False,False,False,False,False,False,False,False,False
3,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,...,False,False,False,False,False,False,False,False,False,False
4,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,...,False,False,False,False,False,False,False,False,False,False

In [20]:
X = df.drop('mpg', axis=1)
y = df['mpg']

In [21]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3, random_state=2)

In [22]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(train_X, train_y)

In [23]:
reg.score(test_X, test_y)

0.6034496307370452

In [24]:
reg.score(train_X, train_y)

1.0

In [25]:
from sklearn import linear_model
lasso_reg = linear_model.Lasso(alpha=50, max_iter=100, tol=0.1)
lasso_reg.fit(train_X, train_y)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [26]:
lasso_reg.score(test_X, test_y)

0.32720213629622286

In [27]:
lasso_reg.score(train_X, train_y)

0.7374468653495972

In [28]:
from sklearn.linear_model import Ridge
ridge_reg= Ridge(alpha=50, max_iter=100, tol=0.1)
ridge_reg.fit(train_X, train_y)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [29]:
ridge_reg.score(test_X, test_y)

0.3968460709696827

In [30]:
ridge_reg.score(train_X, train_y)

0.8035268156426858

In [31]:
from sklearn.linear_model import ElasticNet
elastic_reg = ElasticNet(alpha=50, l1_ratio=0.5, max_iter=100, tol=0.1)
elastic_reg.fit(train_X, train_y)

ElasticNet(alpha=50, max_iter=100, tol=0.1)

In [32]:
elastic_reg.score(test_X, test_y)

0.2995546060627058